include/rapidjson/internal/biginteger.h

rapidjson/reader.h requires  <intrin.h> to be included or _umul128 will be undefined. Below is a minimal example module with the relevant build log:
**lm_jsonreader.cpp:**
--------
#include "lm_jsonreader.h"
#include "rapidjson/reader.h"
--------
**Build log:**
-------
Build started 1/7/2015 1:55:43 PM.
ClCompile:
lm_jsonreader.cpp
c:\users\ez122\source\rapidjson\include\rapidjson\internal\biginteger.h(252): error C3861: '_umul128': identifier not found
-------

Fix an issue with building a reader on Windows x64. 

---

include/rapidjson/reader.h

By replacing the `else return;` paths with a simple `return;`, the Coverity warnings reported in #223 should be silenced.
Closes #223.
_Edit_: Fixed initially failing implementation.

Reader::Parse{Array,Object}: simplify switch

---

include/rapidjson/document.h
test/unittest/documenttest.cpp
test/unittest/valuetest.cpp

1. Fixes `Value(kStringType)` by using short string to store `""` instead of null pointer.
2. Tests `SetString(0, 0)` assertion fail.
3. Assertion on member name in `Accept()`.
Closes #226

Correct Value(kStringType) and more assertions

---

include/rapidjson/reader.h

The code immediately before this changed line goes to the trouble of ensuring that data is aligned at a 16-byte boundary, then goes ahead and uses the unaligned form of the load intrinsic `_mm_loadu_si128`.
Either the code shouldn't bother aligning the data to the start of the whitespace, or it should use the aligned form of the intrinsic.
It's possible that on real-world JSON, better performance is observed by avoiding the serial walk to the boundary and instead using the unaligned load directly. There's no hard _requirement_ to have data aligned here, as far as I know. Was this tested?

Use aligned SSE register load intrinsic.

---

example/serialize/serialize.cpp
include/rapidjson/prettywriter.h
include/rapidjson/writer.h

Currently `RAPIDJSON_HAS_STDSTRING` is only used in `document.h`. It is also useful in `Writer::String` and `PrettyWriter::String`

Add std::string overload to Writer when RAPIDJSON_HAS_STDSTRING defined

---

include/rapidjson/reader.h

* Fix `stackAllocator` parameter name in Doxygen documentation
* Rename parameter/member identifier duplication in `NumberStream` helper

reader.h: warning fixes (closes #235, closes #236)

---

CMakeLists.txt
appveyor.yml
readme.md
test/unittest/CMakeLists.txt
test/unittest/documenttest.cpp
test/unittest/valuetest.cpp

[`AppVeyor`](http://appveyor.com) provides a free service for doing checked Windows builds (similar to [`Travis CI`](https://travis-ci.org) for Linux).
The following [build matrix](https://ci.appveyor.com/project/Kosta-Github/rapidjson/history) has been created for my account:
- `VS2012`, `VS2013`
- `win32`, `x64`
- `Debug`, `Release`
Steps to integrate this into your repo:
1. Sign in into http://appveyor.com with your github account
2. Add your `rapidjson` project to your `AppVeyor` project list
3. Switch to your project setting: https://ci.appveyor.com/project/miloyip/rapidjson/settings
4. Check `Skip branches without appveyor.yml` and press the `Save` button
5. Replace the `badge` link in `readme.md` with a link pointing to your `AppVeyor` account by using the `badge` link from this …

add AppVeyor CI support for checked Windows builds

---

include/rapidjson/error/error.h

In C++'98/03, trailing commas in enumerations are not allowed, but have been introduced in C++11. This patch drops the trailing commas in order to avoid compiler warnings (e.g. GCC with `-pedantic`).
See #9 and http://code.google.com/p/rapidjson/issues/detail?id=49 for previous instances of this issue.

error.h: drop trailing comma in enum

---

readme.md

Doxygen currently does not support images with links, which breaks the current of the build status badges on the front page at https://miloyip.github.io/rapidjson.
This pull-request moves the status badges to a table with the links in the top-row instead:
| [Linux][lin-link] | [Windows][win-link] |
| :---------------: | :-----------------: |
| ![lin-badge] | ![win-badge] |
[lin-badge]: https://travis-ci.org/miloyip/rapidjson.png "Travis build status"
[lin-link]: https://travis-ci.org/miloyip/rapidjson "Travis build status"
[win-badge]: https://ci.appveyor.com/api/projects/status/u658dcuwxo14a8m9/branch/master?svg=true "AppVeyor build status"
[win-link]: https://ci.appveyor.com/project/miloyip/rapidjson/branch/master "AppVeyor build status"
While at it, add a description below the logo and …

readme.md: improve build status rendering by Doxygen

---

include/rapidjson/internal/biginteger.h

Fixes compilation issues with some less common configurations:
- compiler that does not import c stdlib functions into global namespace when including through c++ headers (cstring vs string.h)
- platform with uint32_t typedefed to 32-bit unsigned long and uint64_t to 64-bit unsigned long long - compiler cannot decide between overloads when using unsigned int literal

Compilation fixes

---

RapidJSON.pc.in

Variable in wrong format is not replaced

RapidJSON.pc.in: include dir not set

---

include/rapidjson/document.h
test/unittest/valuetest.cpp

As discovered by @felipegb94, there are missing overloads to the `GenericValue::AddMember<T>` template function, taking an explicit `GenericValue&` as a name and accepting arbitrary primitive values.
This patch adds the missing overloads. The `StringRefType` overload is needed to disambiguate the addition of a string literal as value.
Some tests are added to `TEST(Value, Object)` in `valuetest.cpp`.

GenericValue::AddMember<T>: add missing overload (closes #254)

---

.gitignore
.travis.yml
CMakeLists.txt
appveyor.yml
example/CMakeLists.txt
test/unittest/CMakeLists.txt

The runtimes for the CI builds on Appveyor and Travis CI are currently horribly long.  The main reason for this is the inclusion of the `perftest` even under Debug configurations.  This has not been the case before the cmake migration (#192).
This pull-request excludes `perftest` from the CI configurations `appveyor.yml` and `.travis.yml`.
To avoid merge conflicts, I've merged the pending pull-request #244 (which fixes #240) into this pull-request already. Let's see, what the current status of these pending changes is. ;-)

Skip running perftest on CI debug builds (Appveyer; Travis)

---

.travis.yml

As mentioned in https://github.com/miloyip/rapidjson/issues/266#issuecomment-85660991, this patch drops the usage of SSE4.2 on X86 to avoid running into the Valgrind issue on Clang.

.travis.yml: disable SSE4.2 on 32-bit (closes #266)

---

include/rapidjson/document.h

As reported by @yachoor in https://github.com/miloyip/rapidjson/commit/c1c9ba7c#commitcomment-10434694, the `<string>` header has not been correctly included when `RAPIDJSON_HAS_STDSTRING` is defined by the user.

document.h: include <string>, iff RAPIDJSON_HAS_STDSTRING==1

---

example/tutorial/tutorial.cpp

The insitu parsing example in the tutorial is using a local `char` buffer inside a nested scope.  After leaving the scope, the resulting `Document` object still references this (now invalidated)
memory locations.
Some compilers reuse this space on the stack for other local variables later in the function, corrupting the original document. 
Drop the local scope to extend the lifetime of the buffer, which fixes #273.

tutorial.cpp: fix insitu parsing (closes #273)

---

example/messagereader/messagereader.cpp
include/rapidjson/encodings.h
include/rapidjson/internal/biginteger.h
include/rapidjson/internal/diyfp.h

When compiling with `-pedantic`, some additional warnings are reported by GCC.
* Another trailing comma in an enum in `messagereader.cpp`
* The `unsigned __int128` type is an extension, add an attribute to mark it as such.
* Overflow warnings occur in `encodings.h` due to signedness of `char` on some platforms.  
Hide those for now, as they are all false positives.
No functional changes (intended).

Fixes for GCC with -pedantic

---

doc/CMakeLists.txt
doc/Doxyfile.zh-cn.in
readme.md
readme.zh-cn.md

Just saw the failing build on Travis and fixed it. Please verify that I didn't mess up anything in Chinese. ;-)
* add creation of `Doxygen.zh-cn` to Cmake configuration
* build zh-cn documentation from Cmake as well
* add documentation cross-links to `readme*.md`

fix zh-cn Doxygen generation for Travis CI

---

include/rapidjson/reader.h
test/unittest/readertest.cpp

This is a serious bug. Thank you for reporting.
I have reproduced the error.
The bug is due to `ParseHex4()`. Need to check whether error is generated after calling this function.
I fix this and a similar situation in surrogate pair.

Fix #288 double quote in unicode escape

---

include/rapidjson/internal/dtoa.h
test/unittest/readertest.cpp
test/unittest/writertest.cpp

I have checked both `Reader` and `Writer`.
`Reader` is fine.
`Writer` drops the negative sign for `-0.0`.

Fix #289 negative zero roundtrip (double only)

---

CMakeModules/FindGTestSrc.cmake

If one runs cmake with `cmake -DRAPIDJSON_BUILD_DOC=OFF`, it will fail with the following output:
```
CMake Error at CMakeModules/FindGTestSrc.cmake:20 (find_package_handle_standard_args):
Unknown CMake command "find_package_handle_standard_args".
Call Stack (most recent call first):
test/CMakeLists.txt:1 (find_package)
```
Thus INCLUDE(FindPackageHandleStandardArgs) is required before using find_package_handle_standard_args().

fixed 'Unknown CMake command "find_package_handle_standard_args"'

---

include/rapidjson/reader.h
test/unittest/readertest.cpp

* Supply unittests for parsing of JSON value as root element(RFC7159).
* Assert on impossible code paths.
* For switch-case in `Reader::Transit()` function,
put all impossible code cases and non-enumerated cases under `default:`(also with assertions).

Improve code coverage for iterative parsing

---

include/rapidjson/allocators.h
include/rapidjson/document.h

According to the C/C++ standards, calling `memcpy(NULL, NULL, 0)` is undefined behaviour. Recent GCC versions may rely on this by optimizing NULL pointer checks more aggressively, see [1].
This patch tries to avoid calling std::memcpy with zero elements. As a side effect, explicitly return NULL when requesting an empty block from MemoryPoolAllocator::Malloc.
This may be related to #301. Opening the pull-request as requested by @miloyip.
[1] https://gcc.gnu.org/gcc-4.9/porting_to.html

Avoid calling memcpy with NULL pointers

---

include/rapidjson/internal/diyfp.h

Older versions have no intrin.h, but functions from intrin.h are not used if it's a 32-bit build.

Fixed to build on older versions of 32-bit MSVC

---

doc/faq.md
doc/misc/footer.html

Browser will show a warning when visiting https://miloyip.github.io/rapidjson/ :
> Mixed Content: The page at 'https://miloyip.github.io/rapidjson/' was loaded over HTTPS, but requested an insecure script 'http://rapidjson-doc.disqus.com/embed.js'. This request has been blocked; the content must be served over HTTPS.
This PR fixes this problem, and updates a link to use https. :smile:

Fix warnings when visited via https

---

include/rapidjson/rapidjson.h

gcc 5 sanitizer was complaining about alignment on 64bit platform:
pbjson/rapidjson/document.h:1248:9: runtime error: member call on misaligned address 0x631000028b6c for type 'struct GenericValue', which requires 8 byte alignment
0x631000028b6c: note: pointer points here
74 00 be be be be be be  be be be be be be be be  be be be be be be be be  be be be be be be be be

Fix alignment of 64bit platforms

---

CMakeLists.txt
CMakeModules/FindGTestSrc.cmake

This fix changes the `CMAKE_SOURCE_DIR` variable to relative variables so that rapidjson could be directly included as a submodule in a bigger project, using `add_subdirectory` CMake command.

Fix CMakeLists for include as a thirdparty in projects

---

include/rapidjson/document.h
test/unittest/valuetest.cpp

Try to replace the PR #333
Would like to invite @pah to review.

Add Value::XXXMember(...) overloads for std::string

---

doc/tutorial.md

AddMember requires allocator, this fix keeps all uses of AddMember consistent across the whole tutorial.

Add missing allocator to uses of AddMember

---

doc/faq.md

Add to FAQ: How to clear-and-minimize a document?

---

include/rapidjson/document.h

It unifies the interfaces with Value where kXXXType can be passed
into constructor.
It enables shortcut that helps to avoid extra SetXXX() call following
construction of a document.

Add GenericDocument ctor overload to specify JSON type.

---

include/rapidjson/internal/biginteger.h
include/rapidjson/internal/diyfp.h

Add #pragma intrinsic(_umul128) to avoid unresolved symbol in debug mode for Windows x64

Make it usable with old VC8 (VS2005)

---

include/rapidjson/document.h
include/rapidjson/internal/stack.h
include/rapidjson/internal/swap.h
test/unittest/documenttest.cpp
test/unittest/valuetest.cpp

add GenericDocument<>::Swap

---

include/rapidjson/document.h

As reported in #387, silently moving a `GenericDocument` to a `GenericValue` can lead to object slicing and premature deletion of the owning allocator of the (surviving) `GenericValue`.
To reduce this risk, prohibit move construction/assignment of a `GenericValue` from a `GenericDocument`.

Prohibit C++11 move from Document to Value

---

license.txt

To resolve #377 the license.txt is expanded to clarify that only the JSON_checker code is under the problematic JSON license.

Clarify problematic JSON license (#377)

---

include/rapidjson/internal/dtoa.h

The error message for the original codes is: unary minus operator applied to unsigned type, result still unsigned. 
Added static casting to eliminate this message.

Fix the error when compiled using vs2013

---

include/rapidjson/internal/biginteger.h

There's a copy constructor, but no '=' operator implemented. This is dangerous.

Implement = operator for BigInteger

---

include/rapidjson/filewritestream.h

Fixes warn_unused_result build failure experienced when setting build type to "Release".

check return of fwrite to avoid warn_unused_result build failures

---

include/rapidjson/document.h
include/rapidjson/internal/stack.h

Fix UB in GenericDocument::ParseStream

---

include/rapidjson/document.h
test/unittest/documenttest.cpp

Keeping the DOM unchanged in case of an error is the intended behaviour according to the [documentation] [1].
Instead of forcing the value to `kNullType` before starting the parsing, store the parsed value upon success via regular move.
[1]: https://miloyip.github.io/rapidjson/md_doc_dom.html#ParseError

Keep Document value unchanged on parse error, fixes #437

---

include/rapidjson/reader.h
test/unittest/readertest.cpp

I find support of comments in JSON very useful, especially when one uses JSON as a format for config files. This PR provides a prototype implementation of this feature.
By default comments support is disabled. One should use a new flag `kParseCommentsFlag` to enable the feature, so this implementation is backward compatible and doesn't weaken the standard compliance by default.

Introduce comments support

---

include/rapidjson/document.h
include/rapidjson/reader.h

I took the liberty to add a `return;`  [here](https://github.com/miloyip/rapidjson/compare/master...etiennebatise:missing-breaks-at-switch-statements?expand=1#diff-7a78905da446f733b8019036a99152f9R1453)
This erase the warnings I had on my project when build with `g++ -Wall`

Add break at default switch case statements fix #444

---

.gitignore
rapidjson.autopkg

To create a nupkg, call CoApp's Write-NuGetPackage .\rapidjson.autopkg
-defines:MYVERSION=1.0.2 (or whatever version you want to call it)

Adding coapp definition

---

test/unittest/documenttest.cpp

In the `MoveConstructor`/`MoveAssignment` tests, a check for a `NULL` allocator return has been used to check for the correct moved-from state of a Document. After the merge of #426, the GetAllocator call fails with an assertion, if the allocator of a `GenericDocument` is `NULL`.
Check for the throw, instead of `NULL` in the move-related tests.
Tested with GCC 4.9 on Linux with C++11 enabled.
Reported-by: @woldendans

documenttest.cpp: EXPECT_THROW when checking empty allocator (closes #469)

---

include/rapidjson/document.h

To allow for an UTF16-Document to Parse(UTF8),
the Parse() argument has to be UTF8-compatible.

fix Document::Parse(const Ch*) for transcoding

---

include/rapidjson/document.h
test/unittest/documenttest.cpp

To simplify the error handling, this pull-request adds an implicit conversion of `GenericDocument` to `ParseResult`, allowing code like (already part of the [documentation] [1]):
````cpp
ParseResult ok = doc.Parse(json);
if (!ok) // ...
````
I have been bitten by this error in the docs in the discussion of #479.
Unittests are (slightly) updated as well.
[1]: https://miloyip.github.io/rapidjson/group___r_a_p_i_d_j_s_o_n___e_r_r_o_r_s.html#structrapidjson_1_1_parse_result

GenericDocument: add implicit conversion to ParseResult

---

doc/faq.md
doc/faq.zh-cn.md
doc/sax.zh-cn.md
doc/tutorial.zh-cn.md

在阅读 FAQ 和 SAX 相关部分时，发现有些小错误，修正了部分失效链接
此外，在 FAQ 的 DOM与SAX 部分添加了新的问答，使其与英文版同步

fix typos and dead links in docs

---

include/rapidjson/msinttypes/stdint.h

Instead of commenting that we should, just do include <wchar.h>
with C++ linkage when compiling for Windows on ARM.
Actually, omitting the C linkage really should be enough here.

use <wchar.h> with C++ linkage on Windows ARM

---

include/rapidjson/rapidjson.h

When _MSC_VER and _M_ARM is defined, this is some Windows ARM target
using little-endian byte order.

detect little endian for Microsoft ARM targets

---

include/rapidjson/pointer.h
test/unittest/pointertest.cpp

Add optional unresolvedTokenIndex parameter to Pointer::Get()

---

include/rapidjson/fwd.h
include/rapidjson/prettywriter.h
include/rapidjson/writer.h
test/unittest/fwdtest.cpp
test/unittest/writertest.cpp

Fix #325 
Also provide future additional enhancement mechanism for `Writer` and `PrettyWriter`.

Add encoding validation option for Writer/PrettyWriter

---

include/rapidjson/internal/regex.h
test/unittest/regextest.cpp

Support {0, } and {0, m} in Regex

---

include/rapidjson/document.h
test/unittest/valuetest.cpp

Add Value::Get/SetFloat(), Value::IsLossLessFloat/Double()

---

test/unittest/readertest.cpp

Added some checks to the reader unit tests, to make sure the amount of characters read from the input stream is as expected.
I've simply used the current amount of read characters, to make the tests pass.

Add stream position check to reader unit tests

---

include/rapidjson/internal/dtoa.h
include/rapidjson/writer.h
test/unittest/CMakeLists.txt
test/unittest/dtoatest.cpp

Add Writer::SetMaxDecimalPlaces()

---

include/rapidjson/prettywriter.h
include/rapidjson/writer.h
test/unittest/prettywritertest.cpp
test/unittest/writertest.cpp

Add (Pretty)Writer::RawValue()

---

include/rapidjson/document.h
include/rapidjson/rapidjson.h
test/unittest/valuetest.cpp

Fix #316, #162, #212 
Request for code review

Templated accessors and range-based for

---

include/rapidjson/document.h
include/rapidjson/rapidjson.h
test/unittest/valuetest.cpp

Fix #330 
In x86-64 platform, `RAPIDJSON_48BITPOINTER_OPTIMIZATION` is turned on by default.
This reduces the `sizeof(GenericValue)` from 24 bytes to 16 bytes.
It is interesting to show that, although there is additional calculation for those pointers, the performance does improved due to reduce memory size.
~~~
With RAPIDJSON_48BITPOINTER_OPTIMIZATION=0
[ RUN      ] RapidJson.DocumentParseInsitu_MemoryPoolAllocator_SSE42
[       OK ] RapidJson.DocumentParseInsitu_MemoryPoolAllocator_SSE42 (403 ms)
[ RUN      ] RapidJson.DocumentParseIterativeInsitu_MemoryPoolAllocator_SSE42
[       OK ] RapidJson.DocumentParseIterativeInsitu_MemoryPoolAllocator_SSE42 (433 ms)
[ RUN      ] RapidJson.DocumentParse_MemoryPoolAllocator_SSE42
[       OK ] RapidJson.DocumentParse_MemoryPoolAllocator_SSE42 (457 …

x86-64 48-bit pointer optimization for GenericValue

---

include/rapidjson/schema.h
test/unittest/schematest.cpp

Add move constructor for GenericSchemaDocument

---

include/rapidjson/document.h

GenericObject is a helper class for accessing Value of _object_ type.

Documentation fix.

---

example/CMakeLists.txt
example/parsebyparts/parsebyparts.cpp

Fixed the constructor of `AsyncDocumentParser` to properly initialize all the fields and added pthread link.

#562: example: parsebyparts now compiles with g++-4.9

---

example/capitalize/capitalize.cpp
example/jsonx/jsonx.cpp
example/simplereader/simplereader.cpp
include/rapidjson/document.h
include/rapidjson/prettywriter.h
include/rapidjson/reader.h
include/rapidjson/schema.h
include/rapidjson/writer.h
test/unittest/readertest.cpp
test/unittest/valuetest.cpp

Fast parsing of ints/doubles as strings as described in #560
Note: the null-termination character is never added, always use explicit length

Implemented feature as in #560 (ints/doubles as strings)

---

example/simplewriter/simplewriter.cpp

This makes it painfully obvious that writer expects subsequent key/value pairs.

[simplewriter.cpp] show generated output

---

include/rapidjson/prettywriter.h
test/unittest/prettywritertest.cpp

This change adds PrettyWriter::SetFormatOptions with a corresponding
bitfield enum PrettyFormatOptions. This allows options affecting the
format of the PrettyWriter to be set. The first option to be provided
is kFormatSingleLineArray, which instructs the PrettyWriter to write
arrays on a single line, rather than breaking them up onto a line
per element.

PrettyWriter formatting options.

---

include/rapidjson/pointer.h
test/unittest/itoatest.cpp
test/unittest/strtodtest.cpp

Some type conversions which may lead to precision loss especially on 64-bit platforms are done explicitly. As a result, including rapidjson as a thirdparty into another project which uses -Wconversion flag (for g++ and clang) doesn't break compilation of that project.

do potentially precision-losing conversions explicitly

---

doc/dom.md
include/rapidjson/reader.h
test/unittest/readertest.cpp

This adds `kParseTrailingCommasFlag` to the reader to allow a trailing comma at the end of maps and arrays. This is part of issue #36, adding optional support for relaxed JSON syntax.

Added optional support for trailing commas

---

include/rapidjson/reader.h
test/unittest/CMakeLists.txt
test/unittest/readertest.cpp

RawNumber parsing with non-insitu streams had a lot of issues.  For starters, only copy optimized streams worked, whereas non-copy optimized streams (such as BasicIStreamWrapper) would not work at all.  This is fixed by using a StringStream for the source stream during the encoding phase just before RawNumber is invoked.
For all non-insitu streams, many types of numbers were not parsed into the temporary StackStream properly, particularly negative and scientific numbers.  I created a new ConsumePush method that does the same thing as Consume, except it calls TakePush() instead of Take(), to grab such chars as '.', 'e', '-', etc.
My editor cleans up trailing whitespace as well, so a lot of diffs are from removing trailing whitespace, which I think is a good thing.  I broke those changes up …

RawNumber Improvements / Clang Test Fix / Whitespace Cleanup

---

CMakeLists.txt
appveyor.yml
example/CMakeLists.txt
include/rapidjson/document.h
include/rapidjson/encodedstream.h
include/rapidjson/internal/regex.h
include/rapidjson/pointer.h
include/rapidjson/schema.h
test/unittest/CMakeLists.txt
test/unittest/documenttest.cpp
test/unittest/istreamwrappertest.cpp
test/unittest/readertest.cpp
test/unittest/unittest.cpp
test/unittest/valuetest.cpp

Fix VC warnings

---

example/CMakeLists.txt
example/filterkey/filterkey.cpp
example/filterkeydom/filterkeydom.cpp
readme.md
readme.zh-cn.md

Add filterkey and filterkeydom examples

---

include/rapidjson/rapidjson.h

This makes no difference except that it avoids "warning: macro expansion
producing 'defined' has undefined behavior" messages.

Define RAPIDJSON_HAS_CXX11_RVALUE_REFS directly in clang

---

include_dirs.js
package.json

In order to be able to install rapidjson via npm, I added a package.json and an include_dirs.js as a main.
I use rapidjson  for my own project and I find very useful to install it from npm, also you will have more visibility if you actually publish the package on the npm repo.

npm compliant package.json

---

doc/dom.md
include/rapidjson/reader.h
include/rapidjson/writer.h
test/unittest/readertest.cpp
test/unittest/writertest.cpp

This adds `kWriteNanAndInfFlag` to `Writer` to allow writing of `nan`,
`inf` and `-inf` doubles as "NaN", "Infinity" and "-Infinity",
respectively, and `kParseNanAndInfFlag` to `Reader` to allow parsing
of "NaN", "Inf", "Infinity", "-Inf" and "-Infinity". This is part
of issue #36, adding optional support for relaxed JSON syntax.

Allow options for writing and parsing NaN/Infinity

---

.travis.yml

This should fix the Travis clang builds
https://github.com/travis-ci/travis-ci/issues/6120

switch Clang from broken Ubuntu PPA to upstream binary release

---

.gitignore
doc/tutorial.zh-cn.md

Fix a typo in doc/tutorial.zh-cn.md, and add "Doxyfile.zh-cn" in .gitignore file.

document typo fix and .gitignore update

---

include/rapidjson/document.h
include/rapidjson/schema.h
test/unittest/encodingstest.cpp
test/unittest/istreamwrappertest.cpp
test/unittest/readertest.cpp

This pull-request fixes the warnings on GCC 6 and later as reported in #666 and validated locally.
* `document.h` 
* suppress `-Wterminate` on GCC 6.x and later
* simplify warning handling
* `schema.h`
* drop `RAPIDJSON_NOEXCEPT` from `GenericSchemaDocument` constructor     (calls `RAPIDJSON_NEW` anyway)
* simplify warning handling (avoids `RAPIDJSON_POP` mismatch on Clang)
* `encodingtest.cpp`, `istreamwrappertest.cpp`
* work around `-Wdangling-else`
* `readertest.cpp`
* suppress `-Wdangling-else`

Fix warnings on GCC 6 and later (closes #666)

---

test/unittest/readertest.cpp

GCC 6.x doesn't yet support this warning flag, as reported by @ragnar-ouchterlony in #666.
This has now been verified on Linux, x86_64, with GCC versions
```
g++-5 (Debian 5.4.0-4) 5.4.0 20160609
g++-6 (Debian 6.1.1-7) 6.1.1 20160620
g++-snapshot (Debian 20160612-1) 7.0.0 20160612 (experimental) [trunk revision 237336]
```

readertest: Suppress "dangling-else" warning on GCC 7 and later

---

include/rapidjson/stream.h
test/unittest/stringbuffertest.cpp

Fix inconsistent calling of template functions in PutN in stream.h. When
used with a GenericStringBuffer<<UTF8>, MemoryPoolAllocator>, PutN would call
PutReserve from stream.h, and PutUnsafe from stringbuffer.h. This
resulted in bytes being added to the buffer without allocating space.
This was not an issue when used with the default memory allocator,
because in this case the specialized PutN is used from stringbuffer.h.

Fix buffer overrun using PutN (closes #672)

---

include/rapidjson/schema.h

Prior to this change, a user could incorrectly pass a Document object to
SchemaValidator. This would implicitly construct a SchemaDocument, which
would then be destructed before the validator was used. This caused
unpredictable results including memory corruption and program crashes.
Consider the following snippet, which compiles cleanly but does not behave as expected, because the wrong variable was passed to the SchemaValidator constructor:
```
Document sd;
sd.Parse("{}");
SchemaDocument schema(sd);
SchemaValidator validator(sd);
Document testDoc;
testDoc.Parse("10");
testDoc.Accept(validator);
```

Make GenericSchemaDocument constructor explicit

---

include/rapidjson/document.h

fix rapidjson::value::Get<std::string>() may returns wrong data

---

include/rapidjson/writer.h

Add Flush() for all value types

---

include/rapidjson/document.h

if define RAPIDJSON_HAS_STDSTRING, FindMember use std::string, but it also use internal::StrLen to get the string lengtht,
when it call FindMember(StringRef(name)).
Now use GenericValue construct it, then can use the std::string.size.
now it will be faster.

optimize FindMember  when use std::string

---

include/rapidjson/prettywriter.h

Only String() has the std::string overload currently.

Add std::string overload to PrettyWriter::Key() when RAPIDJSON_HAS_STDSTRING is #defined

---

include/rapidjson/rapidjson.h

From the Debian wiki: https://wiki.debian.org/X32Port
X32 is an ABI for amd64/x86_64 CPUs using 32-bit integers, longs
and pointers. The idea is to combine the smaller memory and cache
footprint from 32-bit data types with the larger register set of
x86_64. The 64-bit registers can make computation more efficient,
and with 8 additional registers available, there is less pressure
compared to i386/i686.
rapidjson makes an incorrect assumption in a check for 64 bit
platforms, and uses __LP64__ exclusively. This fix adds an
additional check for __x86_64__ && __ILP32__ defines, as a very
conservative fix. However, the usage of __LP64__ would be a problem
for other "mixed" applications like ARM ILP32, so a better detection
scheme might be needed in the future.

Fix builds on x32 platform.

---

include/rapidjson/document.h

Since the operator didn't compile, I've explicitly disabled it.

Remove non-compiling assignment operator

---

include/rapidjson/prettywriter.h
include/rapidjson/writer.h
test/unittest/prettywritertest.cpp
test/unittest/writertest.cpp

As `internal::Stack` already has a move constructor, it's trivial to write one for `Writer`.
(Plus, i needed it for a project of mine :smile: .)

Move constructor support for Writer

---

include/rapidjson/stringbuffer.h
test/unittest/stringbuffertest.cpp

Add StringBuffer::GetLength()

---

include/rapidjson/reader.h

Older GCC versions fail compiling RapidJSON due to a warning
include/rapidjson/reader.h:578: error: suggest a space before ';' or explicit braces around empty body in 'while' statement
: warnings being treated as errors

Fix compilation with older GCC versions

---

doc/schema.md

The use of the vertical bar seems to break the rendering of the table in the documentation here:
http://rapidjson.org/md_doc_schema.html
Seems like we can fix it by using html encoding for the vertical bars as described in this post:
http://stackoverflow.com/questions/17319940/how-to-escape-a-pipe-char-in-a-code-statement-in-a-markdown-table/17320389#17320389

FIx typo in documentation

---

include/rapidjson/document.h

winmindef.h defines macros for `min` and `max` which cause several lines in documents.h to be expanded incorrectly whilst only presenting warnings that min and max lacked sufficient arguments.
See: http://stackoverflow.com/questions/22744262/cant-call-stdmax-because-minwindef-h-defines-max for more information.

Fix for winmindef.h defining min/max macros

---

include/rapidjson/document.h

It does not need to depend on GenericDocument event handler any more.
So that stack allocator is not used.
Fix #786

Refactor GenericValue deep-clone constructor

---

include/rapidjson/allocators.h
include/rapidjson/document.h
include/rapidjson/internal/regex.h
include/rapidjson/internal/stack.h
include/rapidjson/pointer.h
include/rapidjson/rapidjson.h
include/rapidjson/schema.h
test/unittest/fwdtest.cpp

**Reason for change**
I am currently integrating RapidJSON into a large project with high performance requirements where custom allocation support is a must. Allocation is done via a custom `scalable_alloc()` function, so the syntax differs from the `new` expression (as does most any custom allocation function's syntax).
So, the object initialization should be `new(scalable_alloc(sizeof(Type)) Type(Args...)`. But the macro's argument `x` supplies the expression `Type(Args...)`. Thankfully, all uses of `RAPIDJSON_NEW` in the library have the form `RAPIDJSON_NEW(AllocatorType())`. This allowed me to hack together a custom type trait that extracts the `Type` part of `Type()` expressions with empty parentheses (works because the expression `Type()` is also a function signature):
``` …
```

Improved customization of RAPIDJSON_NEW macro

---

include/rapidjson/internal/stack.h
include/rapidjson/reader.h

Similar to https://github.com/miloyip/rapidjson/pull/727
But the clang warning I got traced back to the pointer returned by `PushUnsafe`.
I assume this case never happens, so an assert should be sufficient. At least clang is happy with an assertion.

added assertion to help suppress clang warnings

---

doc/internals.zh-cn.md

For Issue #814 , doc/internals.md is translated into Chinese (doc/internals.zh-cn.md).
---
Some nonsense:
I am writing my own XML parser and serializer, this document is very useful for me, so I translated it into Chinese. I hope it can help more people.
Happy New Year 2017!

Translate doc/internals.md into Chinese

---

test/unittest/jsoncheckertest.cpp

Add “filename” to the error message when JsonChecker reports an error.

Improved reporting

---

include/rapidjson/pointer.h

include/rapidjson/pointer.h:243:40: error: 'StrLen' was not declared in this scope
return Append(name, StrLen(name), allocator);

Missing "internal" namespace for StrLen

---

include/rapidjson/prettywriter.h
include/rapidjson/writer.h
test/unittest/prettywritertest.cpp
test/unittest/writertest.cpp

Added new assertion in EndObject to catch error condition where objects
are ended with a key but no matching value.
Added unit tests to verify assertion occurs.

Writer EndObject missing-value fix

---

example/simplepullreader/simplepullreader.cpp

Fix "'MyHandler::type’ should be initialized in the member
initialization list [-Werror=effc++]" errors.
https://github.com/miloyip/rapidjson/issues/874

Fix -Werror=effc++ errors with GNU 6.3.1

---

example/lookaheadparser/lookaheadparser.cpp

Fix clang -Wswitch-enum warnings.
Made NextArrayValue() more robust—now handles error state correctly, and will enter error state if an unexpected state is reached.
Made separate states for each value type to simplify getters.
Simplified implementation of skipping arrays and objects.
Skipping an object now works whether you’ve retrieved the key or not.

Lookahead parser improvements

---

include/rapidjson/reader.h
include/rapidjson/writer.h
test/unittest/readertest.cpp
test/unittest/writertest.cpp

Hi,
There was a bug regarding special characters in strings. Space is 32 (0x20) and code wants to check for 31 and below. However, 31 in hexadecimal is 0x1F, no 0x19.
By the way, I saw some suspicious 0x19999... and 0x9999... checks for i64 overflow. These are likely 0x1FFF and 0xFFF... but I haven't fixed them.
Alejandro

Fixed bug on space hexadecimal encoding

---

include/rapidjson/rapidjson.h

This PR adds support for using C++11 `static_assert` in the `RAPIDJSON_STATIC_ASSERT` macro when it's available.  This has been suggested by @lichray in #924.
For readability, the C++11 implementation is added _before_ the C++03 implementation thus avoiding further conditional nesting.
The token concatenation macro `RAPIDJSON_JOIN`  is used in the diagnostics macros, so the related defines are moved outside the C++03 `RAPIDJSON_STATIC_ASSERT` implementation block.

RAPIDJSON_STATIC_ASSERT: use C++11 static_assert, if available

---

include/rapidjson/rapidjson.h

This issues a warning in gcc7.
While compilers can certainly perform safe integer conversions at compile-time, this warning is not totally unreasonable, considering we added `<auto>` non-type template to C++17, which is both value-dependent and type-dependent, a main template that is "upgraded" from `<int>` to `<auto>` can have `X<0>` and `X<sizeof(char)>` as different specializations, so a type mismatch here is better be warned.
One the other hand I'm curious why we aren't using `static_assert`...
```
diff --git a/include/rapidjson/rapidjson.h b/include/rapidjson/rapidjson.h
index 19a30193..268fd47c 100644
--- a/include/rapidjson/rapidjson.h
+++ b/include/rapidjson/rapidjson.h
@@ -420,6 +420,9 @@ RAPIDJSON_NAMESPACE_END
#define RAPIDJSON_DO_JOIN(X, Y) RAPIDJSON_DO_JOIN2(X, Y)
#define …
```

Fix a non-type template parameter type mismatch

---

doc/faq.md
doc/faq.zh-cn.md
doc/internals.md
doc/internals.zh-cn.md
include/rapidjson/rapidjson.h
include/rapidjson/reader.h
include/rapidjson/writer.h
test/perftest/perftest.h
test/perftest/rapidjsontest.cpp
test/unittest/simdtest.cpp

Verified on aarch64@Ubuntu16.04-64bit. Test log is attached. Pls check.
[test.txt](https://github.com/miloyip/rapidjson/files/946339/test.txt)

Added ARM-Neon support for SIMD.SkipWhitespace*

---

include/rapidjson/internal/regex.h

Add fallthrough attribute to suppress GCC 7.1 warning

---

include/rapidjson/writer.h

Add convenience method Key(std::basic_string<Ch> const&) to Writer

---

include/rapidjson/encodings.h

If storage class is not specified as first in declaration then Intel C++ Compiler 2017 generates message:
message #82: storage class is not first

Storage class is not first - encodings.h

---

include/rapidjson/document.h

As reported by @Llerd in #962, the `copyConstStrings` parameter has not been forwarded recursively to the constructors of object members and array elements.

Fixup #964 by forwarding copyConstStrings recursively

---

include/rapidjson/internal/diyfp.h

To avoid Intel C++ Compiler #1879 warnings:
warning #1879: unimplemented pragma ignored: #pragma intrinsic(_BitScanReverse64)
warning #1879: unimplemented pragma ignored: #pragma intrinsic(_umul128)
See topic:
https://software.intel.com/en-us/forums/intel-c-compiler/topic/405440

Intel C++ Compiler preprocessor guard for #pragma intrinsic - diyfp.h

---

doc/diagram/move2.dot
doc/diagram/move3.dot
doc/tutorial.md

In the move example, the code uses `contacts` when the diagrams use
`contact` (no 's')
The code in the example:
```    Value contacts(kArrayType);
// adding elements to contacts array.
// ...
o.AddMember("contacts", contacts, d.GetAllocator());  // deep clone contacts (may be with lots of allocations)
// destruct contacts.
```

Tutorial: fix typos in examples and broken links

---

include/rapidjson/error/error.h
test/unittest/documenttest.cpp

As reported by @OlafvdSpek in #989, the implicit conversion to `bool` can lead to accidentally compiling expressions.  In addition to the mentioned arithmetic expressions, also using `operator!=` leads to wrong results:
```cpp
ParseResult err = doc.Parse("{]");
if (err != kParseErrorNone) {
// missed! (err --> false, kParseErrorNone --> 0 --> equal!)
}
```
Instead of using an `explicit operator bool` (requires C++11), this PR proposes using the safe-bool idiom.  For completeness, the various `operator!=` overloads are added as well.

ParseResult: improve bool conversion and add operator!=

---

include/rapidjson/document.h
test/unittest/unittest.h
test/unittest/valuetest.cpp

As discussed in #226 already, `Value::GetString()` shall never return a null string.  However, even with assertions enabled, the following code leads to a crash as the non-null assertion in ` GenericStringRef` comes too late:
```cpp
const char* nullPtr = 0;
Value v(StringRef(nullPtr)); // <-- segfault, calls StrLen with NULL
v.SetString(nullPtr, allocator); // <-- segfault, calls StrLen with NULL
```
The fix for this is to embed the assert already before the `StrLen` call :
```cpp
length(((RAPIDJSON_ASSERT(str != 0)), internal::StrLen(str)))
```
which requires changing the ` RAPIDJSON_ASSERT` override in ` unittest.h` to enable usage within expressions (f1ba61c).  All other code  paths are consistently routed through `GenericStringRef` to provide the required invariants.
As an extension …

Improve handling of NULL strings

---

.travis.yml

This is an experiment to move the Travis setup to the new Ubuntu 14.04 (Trusty) images, see
* https://docs.travis-ci.com/user/trusty-ci-environment
* https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
Ideally, this also helps with #993 by using the more recent version of Doxygen from Trusty.

Travis: Switch to Ubuntu 14.04 (Trusty)

---

travis-doxygen.sh

This is a second attempt to close #993 (pre-tested only by running the `travis-doxygen.sh` script locally):
* Upgrade to the latest Doxygen version 1.8.13
* Drop unused variable `DOXYGEN_BIN`
* Reenable `--single-branch` (travis-ci/travis-ci#5225 is closed)

travis-doxygen.sh: upgrade to Doxygen 1.8.13

---

include/rapidjson/document.h

As mentioned by @sagaceilo in https://github.com/miloyip/rapidjson/commit/47c3c1ec9f5c3724c5befb42f8323e760acc1f69#commitcomment-23018046, some assert implementations don't support assertions inside of expressions.
As `internal::StrLen` should continue relying on the not-null guarantee, I moved the `RAPIDJSON_ASSERT+StrLen` sequence into a local function in `GenericStringRef` instead.

GenericStringRef: move assert out of expression

---

include/rapidjson/schema.h
test/unittest/schematest.cpp

Gave up using static binding for null handler, because it cannot be
used with arbitrary handler type. Change `OutputHandler handler_` to
pointer type.

Fix #1017 allOf keyword fail with Writer handler

---

CMakeLists.txt

On certain subsystems `CMAKE_SYSTEM_PROCESSOR` is unavailable due to cross-compilation via MinGW. This causes the expression to be evaluated incorrectly and throw the following message:
> CMake Error at CMakeLists.txt:53 (if):
>   if given arguments:
> 
>     "STREQUAL" "powerpc" "OR" "STREQUAL" "ppc64" "OR" "STREQUAL" "ppc64le"
> 
>   Unknown arguments specified
Nothing fancy. A very simple push to ensure that it is always evaluated string-against-string to avoid issues with less-verbose toolchain files which do not define this variable and leave it empty.

Fix cross-compilation on certain toolchains

---

include/rapidjson/rapidjson.h

Windows ARM64 is also little endian.

Specifies the endian of msvc ARM64 configuration.

---

doc/CMakeLists.txt

When using a MSBuild-based CMake generator like 'Visual Studio 15 2017
Win64', the doc build was failing with the error 'MSB6001: Invalid
command line switch for "cmd.exe". Illegal characters in path.'
This was due to the dependency on Doxyfile*, which wasn't expanded by
CMake.
The fix is to expand this glob in CMake before specifying the custom
command's dependencies.
Partial fix for https://github.com/miloyip/rapidjson/issues/622

Fix Windows doc build MSBuild error MSB6001

---

include/rapidjson/document.h
test/unittest/itoatest.cpp
test/unittest/readertest.cpp
test/unittest/strtodtest.cpp

Guards against min/max being macros.
Sometimes, particularly when Microsoft's windows.h is included, min/max are defined as macros, interfering with use of std::numeric_limits::min() and the like.  To guard against this, the function name is wrapped in an extra set of parenthesis, which inhibits function-style macro expansion.
Two separate commits here: one for document.h and one for test code.

Guard against min/max being macros in a cross-compiler way

---

include/rapidjson/schema.h

Class _internal::GenericRegex<EncodingType, AllocatorType>_ is used by _internal::Schema<SchemaDocumentType>_.
The template parameter for _AllocatorType_ is left to it's default value. This pull request uses Schema::AllocatorType as template parameter and initializes the regex objects created with the schema allocator.
The goal is to use the same (custom) allocator than the one used for _SchemaDocument_. Without this patch, the allocator used is a new instance of the default  _CrtAllocator_, regardless of the allocator used for the _SchemaDocument_.

Use schema allocator for regex

---

include/rapidjson/schema.h

Removing Klocwork static code analysis critical issues:
line 358:
'this->notValidatorIndex_' might not be initialized in this constructor.
line :412
Pointer 'schemaDocument' checked for NULL at line 412 may be passed to function and may be dereferenced there by passing argument this to function 'CreateSchema' at line 419. Also there are 7 similar errors on lines 467 479 511 523 533 538 549.

Removing Klocwork issues from schema.h

---

include/rapidjson/filereadstream.h
include/rapidjson/filewritestream.h

Explicit std name space for fread() and fwrite().

Fix issue #1104 Solaris compilation errors fread()/fwrite()

---

include/rapidjson/document.h

Instead of inheriting from the deprecated `std::iterator` template, define the member typedefs needed for [`std::iterator_traits`](http://en.cppreference.com/w/cpp/iterator/iterator_traits) directly.
Closes #1131.

Avoid inheritance from std::iterator

---

include/rapidjson/reader.h

See [issue #1146](https://github.com/Tencent/rapidjson/issues/1146)

Fix uninitilized member Reader::state_

---

doc/dom.md
doc/dom.zh-cn.md

GetParseOffset函数已经没有了，找到了GetErrorOffset这个函数。

GetParseOffset

---

include/rapidjson/pointer.h
test/unittest/pointertest.cpp

Solves #1108. The default copy constructor of GenericPointer will use the allocator of the copied object. The extra copy constructor that takes an allocator as a parameter is distinct if someone really wants to create a copy with a null allocator.
See  #1108 for details and other possible solutions.

Suggestion for issue #1108

---

include/rapidjson/document.h
test/unittest/valuetest.cpp

We are still using long and unsigned long as s32 and u32 on Microsoft platforms and it was not supported by the TypeHelper.
I added support for long and unsigned long to be Int and UInt when _MSC_VER is definded.
I also added static assert to validate long and unsigned long size in case one day Microsoft change its mind.

Support long and unsined long as int and unsigned on Microsft platforms

---

include/rapidjson/schema.h

Problem: unit test fails unit at SchemaValidator.TestSuite with additionalItems.json on Windows build with VS2010 (possibly with others)
Resolution: changed return value format.
This PR is supposed to repair Appveyor Windows builds that seem to be half-broken since some time.

Fixes #1198

---

include/rapidjson/internal/biginteger.h

The `#pragma intrinsic` preprocessor directive is only implemented on the MSVC compiler. However, the Intel compiler defines `_MSC_VER` to be compatible with MSVC. This results in the following warning when compiling using Intel: `unimplemented pragma ignored` every time the `biginteger.h` file is included.

Ensure a preprocessor directive is only applied to MSVC.

---

include/rapidjson/schema.h
test/unittest/schematest.cpp

Hello,
I think I've encountered a bug. I noticed wrong results when validating a schema referencing a remote schema, which references another remote schema. Here is an example: https://gist.github.com/foxtacles/0deaa03be09cf9820e49cc590ee020c6
`x.json` references `y.json` references `z.json`. The validation should fail (`UK` is not part of the `enum`). However, it succeeds in the current `master` version of RapidJSON.
I found this is because in the `HandleRefSchema` function, `remoteDocument->GetSchema(pointer)` returns a null pointer. In the case of `y.json`, the pointer `/definitions/country` is not part of the internal `schemaMap_`.  Since RapidJSON silently ignores this, the validation succeeds.
I'm not sure if this is intended behaviour - maybe I'm using the library in some wrong …

add remote ref pointer to schemaMap_

---

include/rapidjson/allocators.h

Added macro RAPIDJSON_ALLOCATOR_DEFAULT_CHUNK_CAPACITY to allow default chunk capacity to be lowered for embedded devices with small memory.

Allow user configuration of default chunk capacity.

---

include/rapidjson/rapidjson.h

Fix natural usage with
https://clang.llvm.org/docs/UsersManual.html#clang-cl

Use rvalue refs with clang-cl

---

include/rapidjson/document.h
include/rapidjson/encodings.h
include/rapidjson/internal/meta.h
include/rapidjson/internal/regex.h
include/rapidjson/istreamwrapper.h
include/rapidjson/pointer.h
include/rapidjson/rapidjson.h
include/rapidjson/reader.h
include/rapidjson/schema.h
include/rapidjson/writer.h
test/unittest/istreamwrappertest.cpp
test/unittest/schematest.cpp

Currently rapidjson produces many warning messages when compiling it with clang-cl on windows using MSVC 2017 libraries. The problem is that in this case `_MSC_VER` and `__clang__` are both defined, and the headers doesn't handle this case correctly.
The file `test/unittest/schematest.cpp` had a compile error under gcc with `-Werror=effc++` since `include/rapidjson/internal/regex.h` didn't pop the diagnostic in case of gcc.

Fix compilation on windows with clang

---

include/rapidjson/reader.h
test/unittest/readertest.cpp

When parsing negative exponents, the current implementation takes
precautions for |exp| to not underflow int.
But that is not sufficient: later on [1], |exp + expFrac| is also
stored to an int - so we must ensure that the sum stays within int
representable values.
Update the exp clamping logic to take expFrac into account.
[1] https://github.com/Tencent/rapidjson/blob/master/include/rapidjson/reader.h#L1690

Prevent int underflow when parsing exponents

---

include/rapidjson/schema.h
test/unittest/schematest.cpp

In relation to issue #784 : this pull request enables the `SchemaValidator` to recognise the `default` keyword of a JSON schema, so that:
1. When a none-zero string is given as `default` for a property, a `MissingProperty` error is avoided;
2. The actual content of the string given by the `default` keyword is not checked by the schema at all, only the length of the string is concerned;
3. No modification (such as requested by #784) to the actual JSON document object is made. The programmer is still left with the task to check if the property exist in the document, and if and when `default` is needed, what `default` value it has (by reading the schema document object) .

Avoid `MissingProperty` Error from `SchemaValidator` when a none-zero length value is given as `default` for the property

---

include/rapidjson/rapidjson.h

Based on https://msdn.microsoft.com/en-us/library/hh567368.aspx

MSVC: Autodetect RAPIDJSON_HAS_CXX11_NOEXCEPT, RAPIDJSON_HAS_CXX11_TYPETRAITS

---

include/rapidjson/encodings.h

Some internal macros (COPY/TRANS/TAIL) might conflict with externally define macros with the same sketchy naming.
Prefixing them with RAPIDJSON_ might prevent such conflicts.

Rename a few internal preprocessor macros to avoid naming conflicts

---

include/rapidjson/rapidjson.h

This patch enables various C++11 features if the code is compiled with Developer Studio compiler version 5.14 or higher.

Detect C++11 features for Developer Studio

---

include/rapidjson/internal/itoa.h

Since this part is in a `else if` block after a `if (value < kTen8)`, the condition `value >= kTen8` is necessarily true in that block.

Removing always true if condition

---

include/rapidjson/document.h
include/rapidjson/schema.h
test/perftest/schematest.cpp
test/unittest/schematest.cpp
test/unittest/simdtest.cpp

Recent GCC versions warn about using `memcpy`/`memmove` to write to a class pointer (`-Wclass-memaccess`).  This has been reported multiple times now, but the suppressions in the master branch are not complete.
This PR avoids the warnings by casting the destination pointer to `void*` first.
Closes #1086.
Closes #1205.
Closes #1246.
Additional warnings are fixed / suppressed as discovered during testing:
* Fix `-Wsign-conversion` warnings/errors (a26267d)
* Suppress `-Wformat-overflow` warning/error (1525116)

Fix warnings/errors on GCC 7/8 (-Wclass-memaccess, -Wsign-conversion, -Wformat-overflow) 

---

doc/faq.md
doc/faq.zh-cn.md

GenericDocument contructor requires a pointer to an Allocator, but GetAllocator() only
returns a reference.
Signed-off-by: Julien Courtat <julien.courtat@aqsacom.com>

faq: fix document insertion example

---

test/unittest/readertest.cpp

Add test case on kParseNumbersAsStringsFlag being able to load big ints

---

test/unittest/pointertest.cpp

Without this change clang-7 won't compile `poiontertest.cpp` with the following error:
```
../test/unittest/pointertest.cpp:506:11: error: explicitly assigning value of variable of type 'rapidjson::Pointer' (aka 'GenericPointer<GenericValue<UTF8<> > >') to itself [-Werror,-Wself-assign-overloaded]
q = q;
~ ^ ~
```
See http://releases.llvm.org/7.0.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics.
I thought it is better to use casting instead of silencing the error throughout the codebase

silence clang-7 self-assign-overloaded warning

---

include/rapidjson/schema.h

Free the Malloc()ated memory on std::regex_error exception.

Fix a memory leak for invalid std::regex in Schema.

---

include/rapidjson/internal/regex.h
test/unittest/regextest.cpp

An invalid regex shouldn't kill the process, IsValid() can be checked.

GenericRegex: don't throw/abort on syntax error (unclosed parenthesis).

---

include/rapidjson/filereadstream.h
include/rapidjson/istreamwrapper.h
test/perftest/rapidjsontest.cpp

On (my) linux, perftest reports:
- ~40% gain for FileReadStream (`FileReadStream::Take()` loop),
- ~10% gain for ReaderParse_DummyHandler_FileReadStream.
With the same logic applied to BasicIStreamWrapper, which thus can now
also be created with a user buffer, performances align with those of
FileReadStream (see below, and as also noticed in #1365).
The "unbuffered" versions (added for FileReadStream) work solely with
the internal peekBuffer (Ch[4]) and are measured in perftest.  When
performances don't matter much, they can avoid the use of large
stack/heap buffers.
Though `appveyor` will probably have more trustworthy/relevant numbers, here are some from `perftest` on my linux laptop.
Codebase:
```
[ RUN      ] RapidJson.FileReadStream
[       OK ] RapidJson.FileReadStream (3292 ms)
[ …
```

Optimize FileReadStream and BasicIStreamWrapper.

---

include/rapidjson/schema.h

The Pointer passed to construct the Schema can be from the stack or any
transient storage, so the copy stored in the Schema must have the same
lifetime/allocator as the Schema itself.

Use the allocator of the Schema for its Pointer.

---

example/CMakeLists.txt
example/sortkeys/sortkeys.cpp

We needed a way to sort keys and lost a day to find out how to do it. That is why we are contributing back to this awesome library with an example

added example for sorting keys

---

include/rapidjson/internal/stack.h

The existing check can't be understood by clang-analyze/clang-tidy and reports a null pointer dereference down the line and produces these warnings:
```
include/rapidjson/internal/itoa.h:52:19: warning: Dereference of null pointer [clang-analyzer-core.NullDereference]
*buffer++ = cDigitsLut[d2 + 1];
^
tidy.cpp:7:5: note: Calling 'Writer::Int'
writer.Int(1);
^
include/rapidjson/writer.h:174:72: note: Calling 'Writer::WriteInt'
bool Int(int i)             { Prefix(kNumberType); return EndValue(WriteInt(i)); }
^
include/rapidjson/writer.h:480:23: note: Calling 'i32toa'
const char* end = internal::i32toa(i, buffer);
^
include/rapidjson/internal/itoa.h:115:5: note: Taking false branch
if (value < 0) {
^
include/rapidjson/internal/itoa.h:120:12: note: Calling 'u32toa'
return u32toa(u, buffer); …
```

Silence false positive clang-tidy warning

---

include/rapidjson/istreamwrapper.h

add missing header "ios" for the symbol "std:: streamsize"

add missing header "ios"

---

include/rapidjson/document.h
include/rapidjson/fwd.h

`GenericMember` changed from `struct` to `class`

Fix VS2010 build via disabling copy constructor in GenericMember

---

include/rapidjson/pointer.h

This code was producing a compile error for me on VS2017 (C2105: '--' needs l-value). I've just reused m to be that l-value.

Fix vs2017 compile error C2105: '--' needs l-value

---

include/rapidjson/internal/regex.h
include/rapidjson/rapidjson.h

This is another way to approach #936 #941 #1372 #1513 
Signed-off-by: Ross Younger <crazyscot@gmail.com>

Use C++17 fallthrough tag instead of disabling compiler warning

---

include/rapidjson/schema.h

Build on CentOS 6 was failing due to an uninitialized SizeType variable "index".   Initialized it to 0 to prevent the warning (which was being treated as an error)

Fixed a build issue by initializing "index" in the header file

---

include/rapidjson/schema.h

Removes a duplicate and identical typedef that was causing a
'declaration shadows typedef' (-Wshadow) warning in clang.

Remove shadow typedef

---

include/rapidjson/encodings.h
include/rapidjson/fwd.h
include/rapidjson/reader.h
test/unittest/documenttest.cpp
test/unittest/encodingstest.cpp
test/unittest/fwdtest.cpp

Users can undef the macro 'VALIDATE_CODEPOINT' to disable this feature.

Check before really encoding code points by default.

---

include/rapidjson/document.h

This change comes up with compile time pre-processor directives to
tune the behavior of rapidjson wrt memory consumption. The idea is to
allow each module using this library to choose the right defaults based
on how it consumes memory and what performance it expects.
1. RAPIDJSON_USE_CRTALLOCATOR: If defined allows you to choose CrtAllocator over 
MemoryPoolAllocator. If it is not defined, chooses MemoryPoolAllocator by default.
2. RAPIDJSON_VALUE_DEFAULT_OBJECT_CAPACITY and
RAPIDJSON_VALUE_DEFAULT_ARRAY_CAPACITY: If defined and set to a
value, uses that value for default number of objects/array elements to be pre-allocated. If not 
defined, uses value of 16: the current default.
Verified that all tests pass.

Closes #1643

---

include/rapidjson/internal/clzll.h
include/rapidjson/internal/diyfp.h
include/rapidjson/reader.h
include/rapidjson/writer.h

RAPIDJSON_CLZLL is defined as macro of __builtin_clzll when
using gcc to compile. This introduces two issues:
1. in gcc __builtin_clzll returns int, not uint32_t.
2. __builtin_clzll return is undefined when input x is 0
See: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html
This patch removes RAPIDJSON_CLZLL, merges __builtin_clzll to
internal clzll with input check and return value explicit cast.
Change-Id: Iac4b355dc5e5b4ed9b3f35a640b6b5537e76f22c
Signed-off-by: Jun He <jun.he@arm.com>

Replace RAPIDJSON_CLZLL with internal clzll

---

include/rapidjson/document.h

C++20 features must enable additional functionality, not to change interface completely

Three-way comparison for CLang 10 fix

---

.travis.yml

Start from xenial, Travis supports multiple CPU architectures.
To bump to this version allows test coverage expanding for more
architectures.
See: https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
Change-Id: If61e2d38223dad70b542d6ec0afcf4a433c9debf
Signed-off-by: Jun He <jun.he@arm.com>

ci: upgrade distro to xenial in travis

---

RapidJSONConfig.cmake.in

This way, users can call target_link_libraries against the imported target, which is the recommended way of doing things.

Add a target to RapidJSONConfig.cmake.in

---

RapidJSONConfig.cmake.in

Interface Libraries feature is not available before CMake 3.0
If we add `find_package(RapidJSON)` in CMakeLists.txt and use old cmake to build the project, the cmake progress will failed:
```
CMake Error at CMakeLists.txt:xx (add_library):     
  Cannot find source file:   
INTERFACE
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp .hxx .in .txx     
```
This feature is only available after CMake 3.0, see [this discussion](https://github.com/emil-e/rapidcheck/issues/163) for detail.

Add CMake minimum version required.

---

include/rapidjson/reader.h
test/unittest/readertest.cpp

Report a single low surrogate as kParseErrorStringUnicodeSurrogateInvalid.

Improve surrogate handling (#1738)

---

include/rapidjson/schema.h
test/unittest/schematest.cpp

See comment from @foxtacles here https://github.com/Tencent/rapidjson/pull/1837#issuecomment-777717462.
Scenario is a schema fragment with sub-schemas (eg, `anyOf`). If such a schema is flagged with an error (eg, type wrong) then the sub-validators for those schemas will not get created because `Schema::CreateParallelValidators()` is not called. When the validator is subsequently called for its `EndValue()` event, and the continue-on-error flag is set, it in turn calls `Schema::EndValue()` but this does not check that it has sub-validators before calling `context.validators[i]->IsValid()`. This causes the crash described in https://github.com/Tencent/rapidjson/pull/1837#issuecomment-777717462.
This PR fixes the code by checking that the validator count is greater than zero, and adds a …

After PR 1837, fix crash where simple type with sub-schema has a bad value

---

include/rapidjson/document.h

Hello,
I propose this fix for #1846. I validated it works in C++20 with gcc 11 and causes no regression in the tests suite.
Regards,

Fix recursive operator== call in C++20 (#1846)

---

include/rapidjson/allocators.h
include/rapidjson/rapidjson.h
test/unittest/allocatorstest.cpp

Alternatively to #1865, this proposal (also) fixes StdAllocator with regard to C++17 and later, though the choice here is to keep the same interface for StdAllocator (the C++11 and earlier one) even if compiled with newer C++ versions. Since std::allocator_traits is already available in C++11, there is no need for C++17 or C++20 specifics to allow for that.
While at it, this PR also fixes RAPIDJSON_DELIBERATE_FALLTHROUGH which is not valid with a compiler which __has_cpp_attribute(fallthrough) but still [[fallthrough]] is not usable because -std=C++98 or -std=C++11 is specified.
Sorry for the alternate proposal @sylveon, I thought it would be faster/easier to propose and show some code rather than discuss my proposed changes in your PR..

Make StdAllocator C++17-20 compatible.

---

include/rapidjson/document.h
test/unittest/documenttest.cpp
test/unittest/valuetest.cpp

Extracted from PR #1485, should probably live on its own...
The issue is, from `valuetest.cpp::MergeDuplicateKey()`:
```
for (Value::MemberIterator itr = v.MemberBegin(); itr != v.MemberEnd(); ++itr) {
if (itr->value.Size() == 1)
itr->value = itr->value[0];
...
}
```
Without the fix, in current `GenericValue& operator=(GenericValue&)`, `itr->value.~GenericValue()` gets called before `itr->value.RawAssign(itr->value[0])` and thus `itr->value[0]` may be used after free (with a `kneedFree` allocator).
PS: the VC2013 compilation fix for `sortkeys.cpp` is also included here to pass ci.

Fix (Sub-)Value assignment

---

include/rapidjson/document.h
test/unittest/CMakeLists.txt
test/unittest/platformtest.cpp

On windows a certain include order can break the build, because windows.h defines a macro GetObject
that redefines rapidjson's document GetObject API. This change ensures the macro does not get applied
to rapidjson's definition. For convenience 2 alias methods for GetObject, namely GetObj are added.
fixes #1448

add a workaround for GetObject macro defined by windows.h

---

include/rapidjson/pointer.h
test/unittest/pointertest.cpp

On some compiler, when copy elision is not activated, triggers the bug.
When `Append()` is called it returns a new `Pointer`. And within internal calls of `Append()`, the `return` may call copy constructor, which incorrectly using the source's allocator. This cause problem because the source is temporary and will be destructed.
@smhdfdl
Fix #1899

Fix Pointer::Append() crash for custom allocator on Windows

---

doc/dom.zh-cn.md

original: 
> ... 我们**己**于教程中介绍了 DOM 的基本用法，本节将讲述一些细节及高级用法。
should be:
> ... 我们**已**于教程中介绍了 DOM 的基本用法，本节将讲述一些细节及高级用法。

typo on documentation dom.zh-cn.md: "己于" -> "已于"

---

include/rapidjson/internal/biginteger.h
include/rapidjson/internal/diyfp.h

Issue 1960
Build and unittests pass on x64, arm64 and arm64ec.  
Built on MSVC 2019 16.11.5 + Windows 11 SDK 22000
Unitests executed on  Windows 11 for Arm.

use softintrin on arm64ec

---

include/rapidjson/document.h

When using operator[] on a GenericValue type clang-tidy complains,
appropriately, about the alignment of the buffer used for placement-new
of the "dummy" GenericValue.

Fix the alignment of placement new buffer for GenericValue.

---

include/rapidjson/schema.h

Code in schema.h used the pattern "return a = b;" which caused compliance tools to issue the following false positive:
"error 6282:  : Incorrect operator:  assignment of constant in Boolean context. Consider using '==' instead."
The code does look surprising, so I thought it would be a good idea to simplify it to "a = b; return a;".

Sanitize the code in schema.h

---

include/rapidjson/reader.h

A single character fix for:
error: declaration of ‘is’ shadows a member of ‘rapidjson::GenericReader<rapidjson::UTF8<>, rapidjson::UTF8<> >::NumberStream<rapidjson::GenericStringStream<rapidjson::UTF8<> >, true, false>’ [-Werror=shadow]

fix shadowed variable

---

include/rapidjson/document.h

fix #2007
- Use `::RAPIDJSON_NAMESPACE::MemoryPoolAllocator<::RAPIDJSON_NAMESPACE::CrtAllocator>` instead of `MemoryPoolAllocator<CrtAllocator>` for `RAPIDJSON_DEFAULT_ALLOCATOR` to use it outsie of namespace `RAPIDJSON_NAMESPACE`.
- Use `::RAPIDJSON_NAMESPACE::CrtAllocator` instead of `CrtAllocator` for `RAPIDJSON_DEFAULT_STACK_ALLOCATOR` to use it outsie of namespace `RAPIDJSON_NAMESPACE`.
- Add `StackAllocatorType` for `GenericDocument` class template.

Access to allocator types

---

include/rapidjson/document.h

operator[]() was recently changed to use the existing code in order to
correctly align the returned pointer; however this broke
-Wexit-time-destructors.  Change to a method that is still correctly
aligned but does not generate a destructor.

Avoid exit-time destructors.

---

include/rapidjson/schema.h

The changes here makes the `SchemaValidationContext` destructor robust against a change in control flow between the `validators` and `patternPropertiesValidators` arrays being allocated and initialized.
If the user of rapidjson schema validator provides an allocator that throws on a bad allocation it is possible for the aforementioned arrays to be allocated and not yet initialized. Then on destruction the object will attempt to destruct an uninitialized pointer.
The change in this commit zero's the array that is allocated then checks in the dtor that it is not null before invoking the routine that destructs it.

Make schema dtor robust against exceptions

---

contrib/natvis/rapidjson.natvis

This adjusts two things in the `rapidjson.natvis` file. 
First, string types would display content after the string in the case where the string does not have a null terminator. In this situation the debugger may display garbage after the string. The fix for this is informing the debugger of the length of the string to display (`[data_.s.length]`).
Second, is a fix displaying for rapidjson values in windbg. The natvis must delineate between the current type scope and the type enumeration. Without this change windbg is unable to format the type property - the change here is to prefix the type enumeration with `rapidjson::` in the natvis.
Visual Studio:
windbg:

fixes for natvis

---

include/rapidjson/document.h
test/unittest/simdtest.cpp

These operators call themselves recursively if C++20 semantics are present in the compiler, regardless of standard library support for the operator; therefore the test should be on `__cpp_impl_three_way_comparison`, not `__cpp_lib_[...]`.
This fixes the `Value.EqualtoOperator` test when the language standard is set to C++20 and the standard library does not yet define the library support macro.
To demonstrate, with a reasonably recent clang and libc++ installed (and the gtest module checked out):
```
cmake -DCMAKE_CXX_FLAGS="-std=c++20 -stdlib=libc++ -lc++ -lc++abi -Wno-unused-command-line-argument" .
(make clean; make unittest; cd bin; ./unittest)
```
Prior to these changes, tests segfault in the test `Value.EqualtoOperator` because the operator at document.h:1099 calls itself with …

gate definition of symmetric equality operators on impl, not lib

---

include/rapidjson/allocators.h
include/rapidjson/internal/dtoa.h

These were minor fixes to code that I believe need to be committed and are safe to commit.
include/rapidjson/internal/dtoa.h
in DigitGen function, use ULL suffix to uint64_t numeric constants
static const uint64_t kPow10[] = { 1ULL, 10ULL, 100ULL, 1000ULL, 10000ULL, 100000ULL, 1000000ULL, 10000000ULL, 100000000ULL,
1000000000ULL, 10000000000ULL, 100000000000ULL, 1000000000000ULL,
10000000000000ULL, 100000000000000ULL, 1000000000000000ULL,
10000000000000000ULL, 100000000000000000ULL, 1000000000000000000ULL,
10000000000000000000ULL };
include/rapidjson/allocators.h
#include <limits>
...
template<typename T, typename A>
inline T* Realloc(A& a, T* old_p, size_t old_n, size_t new_n)
{
//RAPIDJSON_NOEXCEPT_ASSERT(old_n <= SIZE_MAX / sizeof(T) && new_n <= SIZE_MAX / sizeof(T)); …

Compile errors on SLES/SLED 11.0 compiler

---

doc/features.md
doc/schema.md
include/rapidjson/error/en.h
include/rapidjson/error/error.h
include/rapidjson/schema.h
test/unittest/schematest.cpp

Addresses issue #1892 by adding support for validating against OpenAPI 2.0 & 3.0 documents. Specifically:
1. Adds the concept of a Specification to schema.h. 
Specification may be a JSON schema draft or an OpenAPI version. 
Recognise all drafts but initially only supports Draft 04, Draft 05, Swagger 2.0 & OpenAPI 3.0.
2. When validating, obtains the schema specification.
Either from the schema if it contains it, or let the user specify it, or default to Draft 04.
3. Adjusts the validation rules according to the specification. 
Draft 04 & Draft 05 are identical in terms of validation rules.
Swagger 2.0 is based on Draft 04 with extensions and restrictions.
OpenAPI 3.0 is based on Draft 05 with extensions and restrictions. 
4. Adds additional error messages for violations of the new rules. …

Code & tests for OpenAPI 2.0 & 3.0 validation

---

include/rapidjson/document.h

A change to the semantics of equality operator rewriting in C++20 (P2468R2: The Equality Operator You Are Looking For) means that operator== may not be rewritten with reversed operands if operator!= is also defined. Since operator!= can normally be synthesized from operator== regardless in this language standard, we can and should avoid defining those when the new language semantics are available.
This fixes the compilation of tests (and probably consuming code) in C++20 onwards for compilers that implement this new semantic, including recent nightly builds of clang-16.
Reference: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2468r2.html

do not define operator!= in C++20

---

include/rapidjson/error/error.h

#2109 
In `/include/rapidjson/error/error.h`
A small typo: `literial` -> `literal`

fix a typo in error.h: literial -> literal

---

test/unittest/simdtest.cpp
test/unittest/uritest.cpp
test/valgrind.supp

This PR is intended to address the SIMD unit test sanitizer problem identified in issue #2019, and any other sanitizer problems that are being thrown up when running other RapidJSON unit tests under `valgrind` .  #2019 contains the list but in summary:
1) SIMD.SkipWhitespace  
- Invalid read of size 16 (the original subject of issue #2019)
- Conditional jump or move depends on uninitialised value(s)
- Use of uninitialised value of size 8
2) Uri.Parse_UTF16 with std::string
- Invalid read of size 32
I am seeing all these on `master` branch (Fedora 36).

Fix the address sanitizer problems - part 1

---

include/rapidjson/schema.h

The Schema class here allows a user to provide a custom allocator which I believe should be used here instead of the default CrtAllocator.  This would be kind of problematic in cases like a client provides an allocator that throws on memory allocation error since the default CrtAllocator does not throw.

Use passed in allocator.

---

include/rapidjson/allocators.h

Without this change there is conflict with max MACRO from Windows header.

Resolve conflict with Windows header about max macro

---

include/rapidjson/internal/biginteger.h
include/rapidjson/internal/diyfp.h

Wrap code checking against __GNUC__ to ensure it is defined. This can cause errors with compilers which do not define this preprocessor value.

Check for __GNUC__ definition

---

include/rapidjson/pointer.h

When using running both Undefined Behavior Sanitizer (UBSan) and Hardware-Assisted Address Sanitizer (HWASan) on Fuchsia, ubsan complained about a pointer overflow when computing the new token->name pointer. This happens because the initial pointer diff takes the offset between two allocations with different tags, so the arithmetic results in a very large diff that gets added to the original token->name ptr which overflows.
Any arithmetic between pointers to two allocations is unspecified behavior, so hwasan+ubsan is catching a bug here. It looks like rapidjson is just attempting to update the name pointers to strings copied into the new nameBuffer_ via this arithmetic, but since these strings and the tokens are in the same buffer, the offset between them should be the same. For each …

Avoid ptrdiff between pointers to different allocations

---

include/rapidjson/writer.h

It's possible alternative to ECMAScript method JSON.stringify()
Introduces flag kWriteNanAndInfNullFlag which have to be used as ```rapidjson::kWriteNanAndInfNullFlag | rapidjson::kWriteNanAndInfFlag``` to stringify nan and inf to null
Closes #2074

Stringify NaN, Inf as null if needs

---

include/rapidjson/schema.h

Remove useless comment block which owns a '\see' cross-reference, but doesn't provide any data after it. This empty cross-reference triggers a compiler warning.
Change-Id: I5c01d57579e5efedcb4bf17b80b06db313a61ab3

Remove empty cross-reference in comment

---

test/unittest/valuetest.cpp

In the BigNestedObject test case of valuetest.c, a dynamically defined format is used that depends on the signedness of the 'SizeType' type. This allows the 'sprintf' function to use the correct format for 'SizeType'.
Change-Id: I97222b699bda6c0ccfc9abbc5977c79e16605f2c

Fixing printf format warning

---

include/rapidjson/schema.h
test/unittest/allocatorstest.cpp

Use static_cast to replace old style cast.
Change-Id: I30e659c8f2aadc02750555b0f041bfd2e1c8004a

Eliminate old style cast warning

---

include/rapidjson/allocators.h

The identifier 'allocator' in the RapidJSON StdAllocator class declaration shadows the identifier 'allocator' in the std::allocator class. To fix this, rename the 'allocator' identifier in the StdAllocator class declaration to a different name.

Rename to fix allocator shadowing

---

include/rapidjson/schema.h
test/unittest/schematest.cpp

The objects with key-value pairs where key=value will always produce zero-value hash.
The algorithm used for keys and string values is the same, so `Hasher::Hash` called on them in `Hasher::EndObject` will produce zero-value, due to xoring in FNV-1a algorithm. Such hash is bug-prone and easy to duplicate, for example: objects
```json
{"value": "value"}
```
and
```json
{"value1": "value1", "value2": "value2" }
```
will produce same hash: `0`
Fixes #2205, fixes #1558

Fix object hashing in schema

---

include/rapidjson/schema.h

One of multipleOf test failed because most floating-point numbers end up being slightly imprecise. And, the check of multipleOf with two double numbers using the dividend (a) and the result of multiplying the multiple after rounding down by the divisor (floor(|a|/|b|)*b) to compare.
Change to using std::numeric_limits::epsilon to check the error of the division result.

Fix comparision of two doubles

---

include/rapidjson/internal/regex.h

In the constructor for GenericRegexSearch, there was an issue with a static_cast casting the result of the Malloc call. The issue was that the stateSet_ member is of type uint32_t*, and there was an attempt to assign an unsigned* to it. On some systems, uint32_t is not equivalent to unsigned, thus yielding a compile error for assigning pointers of different type.

Fix static_cast in regex.h

---

include/rapidjson/document.h

Fix issue #2241 : Visual Studio 2022 (using /std:c++20) new warning 
warning C5232: in C++20 this comparison calls ... recursively

fix Visual Studio 2022 (using /std:c++20) warning C5232: in C… 

---

include/rapidjson/rapidjson.h

On Darwin `__ppc__` is defined  only for 32-bit, so `__ppc64__` has to be present as well.

rapidjson.h: add forgotten ppc64 case

---

include/rapidjson/pointer.h
include/rapidjson/schema.h

When building on Windows with C++ 17 and above we get the warning C4127S
This PR fixes it as it uses `if constexpr` when C++ 17 and above

Fix warning C4127S

---

include/rapidjson/schema.h

Similar to:
**Issue** - https://github.com/Tencent/rapidjson/issues/1033 
**Solution** - https://github.com/Tencent/rapidjson/commit/6e38649ec61e5f4f382c257a6b27698bb55eff61
Fix `std::numeric_limits::max()` compilation confusion on Windows

Guard against max being macros in schema.h

---

include/rapidjson/encodings.h
test/unittest/readertest.cpp

This patch fixes out-of-bound reads while parsing JSONs with kParseValidateEncodingFlag options. Example of fuzzer report:
```
==8041==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x503000785364 at pc 0x55fb97222614 bp 0x7fff724547c0 sp 0x7fff724547b8
READ of size 1 at 0x503000785364 thread T0
#0 0x55fb97222613 in rapidjson::GenericStringStream<rapidjson::UTF8<char>>::Take() rapidjson/include/rapidjson/stream.h:160:24
#1 0x55fb972684b4 in bool rapidjson::UTF8<char>::Validate<rapidjson::GenericStringStream<rapidjson::UTF8<char>>, rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::StackStream<char>>(rapidjson::GenericStringStream<rapidjson::UTF8<char>>&, rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, …
```

Fix out of bounds read with kParseValidateEncodingFlag
