test/unittest/unittest.h
See https://github.com/miloyip/rapidjson/commit/a2a0d161#commitcomment-9838110.
=> unittest.h: make sure to #include <stdexcept>

.gitignore, .travis.yml, CMakeLists.txt, example/CMakeLists.txt, test/unittest/CMakeLists.txt
These changes target all issues mentioned in bug #240.
=> Fixes for #240

test/unittest/stringbuffertest.cpp
=> Fix VS2012 compilation fail in stringbuffertest

CMakeLists.txt
=> Exclude intermediate files from install of in-source build. (Issue #259)

include/rapidjson/rapidjson.h
=> Check libstdc++ version to decide if enable rvalue ref support.

include/rapidjson/document.h, include/rapidjson/internal/diyfp.h, include/rapidjson/internal/dtoa.h, include/rapidjson/internal/ieee754.h, include/rapidjson/reader.h, test/unittest/CMakeLists.txt, test/unittest/documenttest.cpp, test/unittest/readertest.cpp, test/unittest/valuetest.cpp
=> Add -Wfloat-equal and fix all derived warnings 

include/rapidjson/internal/itoa.h
Merge the fix from https://github.com/miloyip/itoa-benchmark/issues/8
=> Try to fix a potential seg fault on some compiler

CHANGELOG.md, include/rapidjson/error/error.h, include/rapidjson/internal/diyfp.h, include/rapidjson/internal/meta.h, include/rapidjson/internal/pow10.h, include/rapidjson/internal/stack.h, include/rapidjson/internal/strfunc.h
=> Include rapidjson.h in error/error.h and internal/*.h

doc/CMakeLists.txt
Complete https://github.com/miloyip/rapidjson/pull/334, I actually forgot to update the CMakeLists.txt under doc folder in my previous pull request.
=> Forgot to update the CMakeLists.txt in doc folder

include/rapidjson/internal/strtod.h, test/unittest/readertest.cpp
=> Fix some numbers parsed incorrectly

doc/faq.md
Credits to @pah who suggested it in comment to #368.
=> Update FAQ 8 with shorter version of clean-and-minimize idiom

doc/faq.md
=> Add to FAQ: How to insert a document node into another document?

example/CMakeLists.txt
=> added missing fields of CMakeList.txt

doc/stream.zh-cn.md
=> doc: 自定义流应当使用 ParseStream 而不是 Parse

include/rapidjson/internal/biginteger.h
Related-to: #404.
Suggested-by: @cosinekitty
=> BigInteger: guard against self-assignment

include/rapidjson/internal/swap.h
\<algorith\> should be \<algorithm\>.
=> Fixed typo

readme.md
Might help some people see things better when skimming.
=> Highlight main features in bold

include/rapidjson/pointer.h, test/unittest/pointertest.cpp
Change the usage of `Value` type in `GenericPointer` to `GenericPointer::ValueType`.
=> Fix #483 by using the correct value type

doc/stream.md, doc/stream.zh-cn.md, include/rapidjson/istreamwrapper.h, include/rapidjson/ostreamwrapper.h, test/unittest/CMakeLists.txt, test/unittest/istreamwrappertest.cpp, test/unittest/ostreamwrappertest.cpp
=> Add iostream wrapper

example/CMakeLists.txt, example/jsonx/jsonx.cpp
=> Add Jsonx example for converting JSON into JSONx (a XML format)

include/rapidjson/stringbuffer.h, include/rapidjson/writer.h, test/perftest/rapidjsontest.cpp, test/unittest/simdtest.cpp
=> Optimize Writer::WriteString() with SIMD

doc/schema.md
Fixed up some wording to the schema documentation
=> Editorial changes to schema documentation

CHANGELOG.md, include/rapidjson/internal/regex.h, include/rapidjson/reader.h, include/rapidjson/schema.h, test/unittest/encodingstest.cpp, test/unittest/regextest.cpp, test/unittest/schematest.cpp, test/unittest/simdtest.cpp, test/unittest/valuetest.cpp, test/unittest/writertest.cpp
In addition to improve coverage, two bugs have been fixed.
=> Improve coverage to 100%

CHANGELOG.md, include/rapidjson/internal/regex.h, test/unittest/regextest.cpp
=> Fix regex crash

include/rapidjson/istreamwrapper.h, include/rapidjson/ostreamwrapper.h
I guess this one is self-explanatory.
=> Added missing include guards in istreamwrapper.h and ostreamwrapper.h

doc/encoding.md, doc/encoding.zh-cn.md
just fix some document problem
=> fix some document problem

include/rapidjson/allocators.h
=> Handle malloc() fail in PoolAllocator

package.json
fix version number in package.json
=> fix version number in package.json

include/rapidjson/schema.h, test/unittest/schematest.cpp
=> fix wrong length in remote schema

example/parsebyparts/parsebyparts.cpp, include/rapidjson/internal/strfunc.h, include/rapidjson/prettywriter.h, include/rapidjson/writer.h
=> Add preconditions in writer and string functions

example/parsebyparts/parsebyparts.cpp
=> Defer thread creation in parsebypart example

include/rapidjson/internal/regex.h, include/rapidjson/schema.h, test/unittest/regextest.cpp
Remove mutable which causes reentrant issue
=> Refactor regex

test/unittest/prettywritertest.cpp, test/unittest/writertest.cpp
=> Remove unncessary std::move()

include/rapidjson/schema.h
Meyers' singleton may not be thread-safe under C++03.
#728
=> Remove singletons in schema classes

include/rapidjson/schema.h
=> Fix nullHandler allocation bug

include/rapidjson/reader.h
=> Remove empty NumberStream::~NumberStream()

rapidjson.autopkg
=> Fix creating the nuget package with Raggles' fork of CoApp

include/rapidjson/schema.h, test/unittest/schematest.cpp
Resolve Issue 848 (segfault in ~Document due to improperly constructed OutputHandler)
=> Null handler fix

doc/sax.md
Added documentation for token-by-token parse APIs.
Minor grammar fixes to existing Reader docs.
=> Token-by-token parser documentation

example/lookaheadparser/lookaheadparser.cpp, include/rapidjson/prettywriter.h, test/unittest/prettywritertest.cpp
Missed PrettyWriter in the initial fix for Issue #889
=> Issue 889 pretty writer

include/rapidjson/document.h, include/rapidjson/schema.h
Just some minor changes Eclipse was complaining about.
=> Minor fixes

include/rapidjson/schema.h, test/unittest/schematest.cpp
=> Fix patternProperties & additionalProperties lead to ASSERT

readme.md, readme.zh-cn.md
* Add alt text for images
* Use https whenever possible
* Update URLs
* Use tools.ietf.org for RFC7159
* Correct indent for sublists
* Trim trailing whitespaces
Preview en: https://github.com/Chocobo1/rapidjson/blob/a31a380cb81c2f20baf4cd7204815e235ea8d2bd/readme.md
Preview zh-cn: https://github.com/Chocobo1/rapidjson/blob/a31a380cb81c2f20baf4cd7204815e235ea8d2bd/readme.zh-cn.md
=> Improve readme.md

include/rapidjson/document.h
=> Assert Type enum lower bound as well

CMakeLists.txt
=> enable cross compiling by adding option to remove -march/-cpu

include/rapidjson/document.h
=> Add MemberCapacity() and MemberReserve() interface for object type.

CHANGELOG.md, doc/dom.md, doc/encoding.md, doc/faq.md, doc/performance.md, doc/pointer.md, doc/sax.md, doc/schema.md, doc/tutorial.md
This is the result of me testing out a WIP source code spell-checker
and your project was the random target this time.
=> fix some typos

example/CMakeLists.txt, example/archiver/archiver.cpp, example/archiver/archiver.h, example/archiver/archivertest.cpp
A simple (de)serialization framework using DOM and SAX API
=> Add archiver example

include/rapidjson/schema.h, test/unittest/schematest.cpp
=> Fix reported violated schema pointer when that schema is remote

CMakeLists.txt, doc/Doxyfile.in, doc/Doxyfile.zh-cn.in, doc/faq.md, doc/internals.md, example/archiver/archiver.h, example/jsonx/jsonx.cpp, example/parsebyparts/parsebyparts.cpp, include/rapidjson/document.h, include/rapidjson/prettywriter.h, include/rapidjson/rapidjson.h, include/rapidjson/reader.h, rapidjson.autopkg, test/perftest/misctest.cpp
Found via `codespell -q 3` in  downstream https://github.com/BlueBrain/Brayns
=> Misc. typos

include/rapidjson/document.h
Hi,
This should fix issue #1086 that you advised we fix by ignoring the warning rather than by changing the code logic.
Cheers,
Romain
=> Ignore GCC 8 warnings.

doc/stream.md, doc/stream.zh-cn.md
I add a few missing includes whose absence made me feel a little confused when reading the doc for the first time.  
Thanks.
=> Adding a few missing includes in the doc

include/rapidjson/reader.h
Added `const` to `Reader` methods where it suitable
=> Added const for Reader methods

include/rapidjson/prettywriter.h, test/unittest/prettywritertest.cpp
This attempts to fix issue #1336: although it seems doing the right thing, I'm not sure this is the right _fix_, as my C++ knowledge is just above 0.
Also, I tried to run the test suite, but I do not understand why I'm hitting the following:
```
$ git submodule update --init
fatal: remote error: want 0a439623f75c029912728d80cb7f1b8b48739ca4 not valid
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'thirdparty/gtest', but it did not contain 0a439623f75c029912728d80cb7f1b8b48739ca4. Direct fetching of that commit failed.
```
Thank you for any advice!
=> Wrap all WriteXxx() calls within EndValue()

doc/tutorial.zh-cn.md
=> fix tutorial error

include/rapidjson/internal/regex.h
This both abides caller's choosen allocator and, if none is provided, avoids creating three ones (states_, ranges_ and Parse()'s).
=> Use passed in allocator for internal regex parser.

doc/pointer.zh-cn.md
=> Update pointer.zh-cn.md : fix typo

.travis.yml, travis-doxygen.sh
=> fix travis build

readme.md
add contributing section in readme.md, introduced the basic cooperation process.
=> add contributing section in readme.md

doc/stream.md
=> Fix simple typo: drived -> derived

include/rapidjson/internal/biginteger.h
https://github.com/Tencent/rapidjson/commit/de6681e295726f528a4b449ca51c940972eb6f1a#commitcomment-37645051
=> Fix intel compiler macro

include/rapidjson/prettywriter.h
=> PrettyWriter constructor uninitialized member

contrib/natvis/rapidjson.natvis
1. Determine the correct type of string based on encoding
2. Omit string pointer address
=> Update Visual Studio Visualizer

include/rapidjson/document.h, test/unittest/pointertest.cpp
Allows resolution of JSON Pointer on Object and Array
=> Add implicit conversion from Object and Array to Value (#1404)

include/rapidjson/schema.h
https://github.com/Tencent/rapidjson/issues/1778
=> fix 1778  (part 1)

include/rapidjson/allocators.h
=> Fixed -Wshadow warning.

include/rapidjson/reader.h, test/unittest/readertest.cpp
Changed instances of >> to > > as was failing compilation with Apple clang version 12.0.5.
=> Resolving issue #1948

include/rapidjson/document.h
Reverts Tencent/rapidjson#1987
=> Revert "Fix the alignment of placement new buffer for GenericValue."

CMakeLists.txt
=> CMakeLists: fix optflags for ppc

include/rapidjson/document.h, test/unittest/valuetest.cpp
In case sso use memmove to avoid memory overlapping issues
=> Fix issue 2307
